version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TAG: v1.0
    container_name: TaskTrakBackend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./task_trak:/app/task_trak
